### ISSUE TITLE
Update widget for latest dev version

### ISSUE THREAD

**Issue by cuthberts** [tr3vorm/cmv-projections-widget#13]
Hi Trevor,

What are the odds of getting the projection widget to comply with the latest development CMV app?

At the moment I'm getting the following errors using Chrome and IE on Windows 7.
![image](https://user-images.githubusercontent.com/8953510/32265849-f79582aa-bf38-11e7-8b40-9b63447961a9.png)

Thank you in advance

**Comment by tr3vorm** [comment]
I was unaware of this. We are still using it so will check this tomorrow (UTC+13) and get back after we have investigated further.

**Comment by tr3vorm** [comment]
I am not seeing any errors in my configuration. How do you replicate this? Just by clicking on the map? Do any coordinates appear?

And what does your config look like?

**Comment by duckblaster** [comment]
You could try adding `'diji/form/ToggleButton',` to the projection.js file after the `'dojo/text!./Projection/templates/Projection.html',` line and see if that fixes it.

**Comment by cuthberts** [comment]
@tr3vorm it happens as soon as I click on the widget to expand it.
![image](https://user-images.githubusercontent.com/8953510/32299144-95cd4984-bfa8-11e7-98f2-55d2ed1a0896.png)

The viewer.js config is as below
![image](https://user-images.githubusercontent.com/8953510/32299260-16b90560-bfa9-11e7-9630-5375a7683763.png)

@duckblaster I tried adding the extra piece of code, but the error changed to the following, instead of the previous issue, at the same stage as above.
![image](https://user-images.githubusercontent.com/8953510/32299173-b9fb11a6-bfa8-11e7-801b-2df14ed0ba7f.png)

**Comment by tr3vorm** [comment]
We cannot reproduce the issue even after updating all the code to the current branch, so not able to help any further at this stage sorry.

**Comment by cuthberts** [comment]
Ok, thank you for looking into it

**Comment by tr3vorm** [comment]
My only other thought is that there is something else causing it. Maybe try isolating that widget in the config by removing other widgets?

**Comment by cuthberts** [comment]
I turned off all the other widgets but still no success. I'll keep trying to find the issue, but appreciate the help.

**Comment by cuthberts** [comment]
I've managed to get the widget working with Chrome, but in IE it's not converting the coordinates.
![image](https://user-images.githubusercontent.com/8953510/32420957-f7a227a6-c2e6-11e7-95fe-510999b5e8be.png)

Do you believe this would be because of permissions to the epsg.io projection files?

**Comment by tr3vorm** [comment]
I think it may be due to using a mixture of http and https? Chrome/IE handle this differently. I checked my config here and IE works fine. Any clues with development tools (F12) on? Any JavaScript errors?

**Comment by cuthberts** [comment]
It looks like there might be an issue with the individual projection js files the widget uses.
![image](https://user-images.githubusercontent.com/8953510/32464955-ec4746e8-c395-11e7-8f68-5c913f543527.png)

**Comment by cuthberts** [comment]
There's nothing in the development tools in IE when the Projection widget is initiated. Although i think you might be right about the http and https. Looking into Fiddler my companies security system seems to be flagging the projection .js files that are used by the widget. I'll try downloading the .js files and storing them locally, which might help.

**Comment by tr3vorm** [comment]
I had a quick look at my code - I am assuming you have the latest release of this widget. The call to epsg.io uses http or https based on the CMV viewer. So there no issue there with mixing protocols. 

```javascript
        proj4BaseURL: '//epsg.io/',
        //  options are ESRI, EPSG and SR-ORG
        // See http://spatialreference.org/ for more information
        baseProjection: null,
        proj4Catalog: 'EPSG', // case sensitive!

**Comment by cuthberts** [comment]
I ended up downloading the projection .js files and hosting them on my server and now it's all fine. Thank you for all your help.

**Comment by tr3vorm** [comment]
Sorry I couldn't work out why it was failing but glad to hear it is working for you.
